bookmark_list_friend:
  url: /bookmark/list/:id
  param: { module: bookmark, action: list }

bookmark_list:
  url: /bookmark/list
  param: { module: bookmark, action: list }


bookmark_delete:
  url: /bookmark/delete/:id
  class: sfDoctrineRoute
  options: { model: Bookmark, type: object }
  param: { module: bookmark, action: delete }
  requirements:
    id: \d+
    sf_method: [get, post]

bookmark_add:
  url: /bookmark/add
  param: { module: bookmark, action: add }
  requirements:
    sf_method: [get]

bookmark_add_post:
  url: /bookmark/add/post
  param: { module: bookmark, action: add }
  requirements:
    sf_method: [post]