<?php

/**
 * PluginBookmarkCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBookmarkCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBookmarkCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBookmarkComment');
    }
}